const bcrypt = require('bcrypt');

const data = {
    patients: [
        {
            // _id: '1',
            username: 'Azkaban',
            email: 'christianjay.ascano@tup.edu.ph',
            password: bcrypt.hashSync('azkaban123', 8),
            fullName: 'Christian Jay Ascaño',
            address: 'Cavite',
            sex: 'Male',
            birthMonth: '01',
            birthDate: '08',
            birthYear: '2000',
            contact: '09123456789',
            // date: '2021-08-01',
            // timeRequested: '03:21',
            // timeResponded: '',
            // status: 'Accepted',

            // Medical Information
            chkDiabetes: false,
            chkHeartDisease: false,
            chkHeartFailure: true,
            chkStroke: true,
            chkAsthma: false,
            chkArthritis: true,
            chkCOPD: false,
            chkBloodPressure: true,
            chkAlzheimer: false,
            chkCancer: false,
            cancerInfo: '',
            chkOthers: true,
            othersInfo: 'Primary Complex',
            chkFood: true,
            foodInfo: 'Lycopene',
            chkMedication: false,
            medicationInfo: '',
            chkEnvironmental: true,
            environmentalInfo: 'Pollen, Dust',
            surgeryCount: '1',
            surgeryInfo: 'Left Arm',
            surgeryMonth: '08',
            surgeryDate: '08',
            surgeryYear: '2020',
            surgeryHospital: 'St. Lukes Medical Hospital',
        },
        {
            // _id: '2',
            username: 'Ilarina',
            email: 'rachel.ilarina@tup.edu.ph',
            password: bcrypt.hashSync('ilarina123', 8),
            fullName: 'Rachel Ilarina',
            address: 'Malabon City',
            sex: 'Female',
            birthMonth: '02',
            birthDate: '13',
            birthYear: '2000',
            contact: '09123456789',
            // date: '2021-08-02',
            // timeRequested: '12:18',
            // timeResponded: '',
            // status: 'Rejected',
            
            // Medical Information
            chkDiabetes: false,
            chkHeartDisease: false,
            chkHeartFailure: true,
            chkStroke: true,
            chkAsthma: false,
            chkArthritis: true,
            chkCOPD: false,
            chkBloodPressure: true,
            chkAlzheimer: false,
            chkCancer: false,
            cancerInfo: '',
            chkOthers: true,
            othersInfo: 'Primary Complex',
            chkFood: true,
            foodInfo: 'Lycopene',
            chkMedication: false,
            medicationInfo: '',
            chkEnvironmental: true,
            environmentalInfo: 'Pollen, Dust',
            surgeryCount: '0',
            surgeryInfo: '',
            surgeryMonth: '',
            surgeryDate: '',
            surgeryYear: '',
            surgeryHospital: '',
        },
        {
            // _id: '3',
            username: 'Alonchii',
            email: 'alonzo.ramos@tup.edu.ph',
            password: bcrypt.hashSync('ramos123', 8),
            fullName: 'Alonzo Ramos',
            address: 'Valenzuela City',
            sex: 'Male',
            birthMonth: '11',
            birthDate: '03',
            birthYear: '2000',
            contact: '09123456789',
            // date: '2021-08-03',
            // timeRequested: '23:42',
            // timeResponded: '',
            // status: '',

            // Medical Information
            chkDiabetes: false,
            chkHeartDisease: false,
            chkHeartFailure: true,
            chkStroke: true,
            chkAsthma: false,
            chkArthritis: true,
            chkCOPD: false,
            chkBloodPressure: true,
            chkAlzheimer: false,
            chkCancer: false,
            cancerInfo: '',
            chkOthers: true,
            othersInfo: 'Primary Complex',
            chkFood: true,
            foodInfo: 'Lycopene',
            chkMedication: false,
            medicationInfo: '',
            chkEnvironmental: true,
            environmentalInfo: 'Pollen, Dust',
            surgeryCount: '1',
            surgeryInfo: 'Left Arm',
            surgeryMonth: '03',
            surgeryDate: '12',
            surgeryYear: '2017',
            surgeryHospital: 'St. Lukes Medical Hospital',
        },
        {
            // _id: '4',
            username: 'papajujubajuju',
            email: 'juliusanthony.villa@tup.edu.ph',
            password: bcrypt.hashSync('villa123', 8),
            fullName: 'Julius Anthony A. Villa',
            address: '343-O M.Ramoy Compound, Quirino Highway, Sangandaan, Quezon City',
            sex: 'Male',
            birthMonth: '12',
            birthDate: '08',
            birthYear: '1999',
            contact: '09154547585',
            // date: '2021-08-03',
            // timeRequested: '23:42',
            // timeResponded: '',
            // status: '',

            // Medical Information
            chkDiabetes: false,
            chkHeartDisease: true,
            chkHeartFailure: true,
            chkStroke: false,
            chkAsthma: true,
            chkArthritis: false,
            chkCOPD: false,
            chkBloodPressure: false,
            chkAlzheimer: false,
            chkCancer: false,
            cancerInfo: '',
            chkOthers: true,
            othersInfo: 'Primary Complex',
            chkFood: false,
            foodInfo: '',
            chkMedication: false,
            medicationInfo: '',
            chkEnvironmental: true,
            environmentalInfo: 'Pollen, Dust',
            surgeryCount: '0',
            surgeryInfo: '',
            surgeryMonth: '',
            surgeryDate: '',
            surgeryYear: '',
            surgeryHospital: '',
        },
    ]
}

module.exports = data;